[package]
name = "dll_handler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libffi = "3.2.0"
libloading = "0.8.0"

[build-dependencies]
cc = "1.0.79"
