[package]
name = "arsenal-vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arsenal-globals = { path = "../arsenal-globals" }
libc = "0.2.147"
